name: c2bm
channels:
  - pyg
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pytorch:pytorch>=2.1
  - torchvision>=0.17.1
  - networkx
  - lightning
  - cdt
  - fpdf2
  - requests
  - python-dotenv 
  - hydra-core=1.3.*
  - numpy
  - pandas
  - tqdm
  - scipy
  - scikit-learn
  - seaborn
  - tqdm
  - openpyxl
  - huggingface_hub
  - transformers
  - pyg:pyg=*=*cu*
  - pyg:pytorch-scatter
  - pyg:pytorch-sparse
  - pytorch:pytorch-cuda
  - pip
  - pip:
    - wandb
    - plotly
    - kaleido
    - gdown
    - causal-learn
    - langchain_community
    - langchain
    - langchain_core
    - langchain_huggingface
    - accelerate>=0.26.0
    - bnlearn
    - nltk
    - mistralai
    - openai
    - requests
    - beautifulsoup4
    - lxml
    - duckduckgo_search
    - hydra-list-sweeper
    - pytorch-minimize